### ISSUE TITLE
Make compaction staging optional

### ISSUE THREAD

**Issue by hloeung** [juju/mgopurge#36]
Hi,

mgopurge by default runs the compaction stage. It isn't usually disk space issues one runs into and, as I'm being told, the version of mongo used, compacting collections doesn't help with secondarys' disk space.

The compaction stage also seems to be the one that takes the longest, especially when compacting the various logs collections.

Can we make that optional? Have a command line option to include running the compaction stage.

Thanks

**Comment by jameinel** [comment]
It is already optional, and you would specify it by passing "-stages" and
leaving out compact, but the current mechanism for doing it means you need
to know what *all* the stages are, and supply all of them except the one
you want to omit.
Certainly it would be cleaner to have something like "-skip-stage compact"
to blacklist one instead of only whitelisting them.
