### ISSUE TITLE
mgopurge should compact all collections

### ISSUE THREAD

**Issue by axinojolais** [juju/mgopurge#6]
Hi,

It appears that repairDatabase doesn't give back the disk space previously used. The "compact" command (https://docs.mongodb.com/manual/reference/command/compact/) does, so I believe it should be run by mgopurge.

It doesn't compact all nodes though, so it must be run manually on the secondaries...

Thanks

**Comment by jameinel** [comment]
It also doesn't like it if you run it on a primary, as it blocks running
operations. (you have to set force:true.) So it would be possible to run
this as part of the greater-purge (especially after purging the txns
collection), but shouldn't be run regularly elsewhere.

According to the docs, its safe to run on secondaries while things are
live, as it assumes they'll catch up once compact is done.

John
=:->

**Comment by axinojolais** [comment]
Indeed it blocks running operations, so it should be part of "the stages that can't be run when jujuds are alive", I'd say.

**Comment by mjs** [comment]
Indeed... as a general rule mgopurge should never be run when any of the controller machines are running. The "prune" stage is the only one which is somewhat safe to run while the system is live. 

According to the MongoDB docs, repairDatabase is supposed to give back disk space, but only on the host you run it on. You need to run it on each node separately in order to get back disk space everywhere.

repairDatabase is inconvenient because it requires 2GB + the size of the DB of free space so I will change mgopurge to use the `compact` command (with `force:true`) on each collection instead. `compact` doesn't release disk space when the mmapv1 storage engine is in use (i.e. Juju 1.x) so mgopurge will have to continue using `repairDatabase` there.

**Comment by mjs** [comment]
Fixed by e40c8acab9790a54922d7ecd62dd3e4e5032d02b

**Comment by axinojolais** [comment]
https://github.com/juju/mgopurge/commit/e40c8acab9790a54922d7ecd62dd3e4e5032d02b only compacts the collections of the "juju" database, could it also compact the collections of the other databases ?

**Comment by jameinel** [comment]
Since we aren't removing anything from the other collections, is there
actually an advantage to compacting them?

John
=:->

**Comment by axinojolais** [comment]
mgopurge isn't, but juju controls the size of the logs.logs and statuseshistory collections. If you have, say, a spike of logs, then the collection will grow, and then later when juju removes the records from the spike (because they have expired), the collection will return back to its normal size, but the space will not be reclaimed by the system.
